# Permalinks
permalink:           pretty

# Setup
title:               PMHC-MDS
url:                 https://www.pmhc-mds.com

# About/contact
author:
  name:              'Logicly'
  email:             'info@logicly.com.au'

exclude: [node_modules,vendor,src,gulpfile.js,bower_components,bower.json,README.md,static,package.json,'*.sh',nginx.d]
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
source:      _source
destination: _site
future: true
