services:
  site:
    command: jekyll serve --host 0.0.0.0 --livereload
    #command: bundle update
    image: jekyll/jekyll:4
    volumes:
      - $PWD:/srv/jekyll
      - $PWD/vendor/bundle:/usr/local/bundle
    ports:
      - 4000:4000
      - 35729:35729
