version: '3.9'

services:
  site:
    command: jekyll serve
    #command: bundle update
    image: jekyll/jekyll:4
    volumes:
      - $PWD:/srv/jekyll
      - $PWD/vendor/bundle:/usr/local/bundle
    ports:
      - 4000:4000
      - 35729:35729
#      - 3000:3000
#      -   80:4000
