#!/usr/bin/env bash
set -e # halt script on error

docker run \
  -it --rm --label=jekyll \
  --volume=$(pwd):/srv/jekyll \
  jekyll/jekyll:3.8 bash -c "bundle install; bundle exec jekyll build"

docker run \
  -it --rm --label=html-proofer \
  --volume=$(pwd)/_site:/srv/site \
  18fgsa/html-proofer /srv/site --disable-external --empty-alt-ignore --url-ignore "/^#$/" \
  || echo "Fail!"

docker run \
  -it --rm --label=html5validator \
  --volume=$(pwd)/_site:/app/site \
  stratdat/html5validator \
  || echo "Fail!"
