#!/usr/bin/env bash

set -e # halt script on error

key=$encrypted_ff291805c3de_key
iv=$encrypted_ff291805c3de_iv

openssl aes-256-cbc \
  -K $key \
  -iv $iv \
  -in .travis/deploy-key.enc \
  -out .travis/deploy-key -d

eval "$(ssh-agent -s)" #start the ssh agent
chmod 600 .travis/deploy-key
ssh-add .travis/deploy-key
git config --global push.default simple
git add -A
git diff --quiet --exit-code --cached || git commit -m 'Add build artefacts'
git remote add production git@github.com:strategicdata/pmhc-mds.com.git
git push production HEAD:production --force
