#!/usr/bin/env bash

set -e # halt script on error

# Edit .gitignore to publish
perl -n -i -e "print unless /^_site\/$/" ./.gitignore
git add .
git commit -m "Commit build artefacts for publishing"
git remote add pages git@github.com:logicly-au/pmhc-mds.com.git
git push pages `git subtree split --prefix _site 2> /dev/null`:gh-pages --force
git reset HEAD~
git checkout .gitignore
