name: Build and publish gh-pages website

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # cache gems
      - name: Cache
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Jekyll
      - name: Build site with Jekyll
        uses:  helaili/jekyll-action@v2
        with:
          build_only: true
          build_dir: _site
          jekyll_src: _source
        env:
          JEKYLL_LOG_LEVEL: debug


      - name: HTML proofer
        uses: docker://18fgsa/html-proofer
        with:
          args: /github/workspace/_site --disable-external --empty-alt-ignore --url-ignore "/^#$/"

      - name: HTML5 validator
        uses: docker://stratdat/html5validator
        with:
          entrypoint: html5validator
          args: --root /github/workspace/_site

      # push to ghpages
      - name: Check GitHub Pages status
        uses: crazy-max/ghaction-github-status@v3
        with:
          pages_threshold: major_outage

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages-test
          build_dir: _site
          fqdn: pmhc-mds.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

